name: Build e Testes do Sistema Escolar

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Executar testes
        run: mvn test

      - name: Fazer build
        run: mvn package

      - name: Publicar JAR
        uses: actions/upload-artifact@v4
        with:
          name: Sistema_Escolar
          path: target/*.jar
